name: "Kustomize actions for GitHub workflows"
description: "Kustomize actions Kubernetes deployments"
inputs:
  install:
   description: "Kustomize installation requirement"
   required: true
  bot-name: 
    description: "GitHub Auto Commit Name"
    required: false
  path:
    description: "Kustomize folder path"
    required: false
  image:
    description: "Image Name"
    required: false
  event_type:
    description: "GitHub trigger event type"
    required: false
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: execute_action.sh ${{ inputs.install }} ${{ inputs.bot-name }} ${{ inputs.path }} ${{ inputs.image }} ${{ inputs.event_type }}
      shell: bash