name: "Kustomize actions for GitHub workflows"
description: "Kustomize actions Kubernetes deployments"
inputs:
  bot-name: 
    description: "GitHub Auto Commit Name"
    required: true
  path:
    description: "Kustomize folder path"
    required: true
  image:
    description: "Image Name"
    required: true
  event_type:
    description: "GitHub trigger event type"
    required: true
  version:
    description: "Kustomize version"
    required: true
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: execute_action.sh ${{ inputs.bot-name }} ${{ inputs.path }} ${{ inputs.image }} ${{ inputs.event_type }} ${{ inputs.version }}
      shell: bash